proxmox_sdn:
  zone:
    name: virtnet
    type: simple
    dhcp: dnsmasq
    ipam: pve
    mtu: 1460

  vnets:
    - name: vnet1
      alias: Production Network
      isolate_ports: false
      subnet: 10.0.12.0/24
      gateway: 10.0.12.1
      dhcp_start: 10.0.12.100
      dhcp_end: 10.0.12.199
      snat: true

    - name: vnet0
      alias: Staging Network
      isolate_ports: true
      subnet: 10.0.11.0/24
      gateway: 10.0.11.1
      dhcp_start: 10.0.11.100
      dhcp_end: 10.0.11.199
      snat: false

    - name: itsa1
      alias: ITSec A1
      isolate_ports: false
      subnet: 10.10.11.0/24
      gateway: 10.10.11.1
      dhcp_start: 10.10.11.100
      dhcp_end: 10.10.11.199
      snat: true

    - name: itsa2
      alias: ITSec A2
      isolate_ports: false
      subnet: 10.10.12.0/24
      gateway: 10.10.12.1
      dhcp_start: 10.10.12.100
      dhcp_end: 10.10.12.199
      snat: true

    - name: itsa3
      alias: ITSec A3
      isolate_ports: false
      subnet: 10.10.13.0/24
      gateway: 10.10.13.1
      dhcp_start: 10.10.13.100
      dhcp_end: 10.10.13.199
      snat: true

    - name: itsa4
      alias: ITSec A4
      isolate_ports: false
      subnet: 10.10.14.0/24
      gateway: 10.10.14.1
      dhcp_start: 10.10.14.100
      dhcp_end: 10.10.14.199
      snat: true

    - name: itsb1
      alias: ITSec B1
      isolate_ports: false
      subnet: 10.10.21.0/24
      gateway: 10.10.21.1
      dhcp_start: 10.10.21.100
      dhcp_end: 10.10.21.199
      snat: true

    - name: itsb2
      alias: ITSec B2
      isolate_ports: false
      subnet: 10.10.22.0/24
      gateway: 10.10.22.1
      dhcp_start: 10.10.22.100
      dhcp_end: 10.10.22.199
      snat: true

    - name: itsb3
      alias: ITSec B3
      isolate_ports: false
      subnet: 10.10.23.0/24
      gateway: 10.10.23.1
      dhcp_start: 10.10.23.100
      dhcp_end: 10.10.23.199
      snat: true

    - name: itsb4
      alias: ITSec B4
      isolate_ports: false
      subnet: 10.10.24.0/24
      gateway: 10.10.24.1
      dhcp_start: 10.10.24.100
      dhcp_end: 10.10.24.199
      snat: true

    - name: cybera1
      alias: Cyber A1
      isolate_ports: false
      subnet: 10.20.11.0/24
      gateway: 10.20.11.1
      dhcp_start: 10.20.11.100
      dhcp_end: 10.20.11.199
      snat: true

    - name: cybera2
      alias: Cyber A2
      isolate_ports: false
      subnet: 10.20.12.0/24
      gateway: 10.20.12.1
      dhcp_start: 10.20.12.100
      dhcp_end: 10.20.12.199
      snat: true

    - name: cybera3
      alias: Cyber A3
      isolate_ports: false
      subnet: 10.20.13.0/24
      gateway: 10.20.13.1
      dhcp_start: 10.20.13.100
      dhcp_end: 10.20.13.199
      snat: true

    - name: cybera4
      alias: Cyber A4
      isolate_ports: false
      subnet: 10.20.14.0/24
      gateway: 10.20.14.1
      dhcp_start: 10.20.14.100
      dhcp_end: 10.20.14.199
      snat: true

    - name: cyberb1
      alias: Cyber B1
      isolate_ports: false
      subnet: 10.20.21.0/24
      gateway: 10.20.21.1
      dhcp_start: 10.20.21.100
      dhcp_end: 10.20.21.199
      snat: true

    - name: cyberb2
      alias: Cyber B2
      isolate_ports: false
      subnet: 10.20.22.0/24
      gateway: 10.20.22.1
      dhcp_start: 10.20.22.100
      dhcp_end: 10.20.22.199
      snat: true

    - name: cyberb3
      alias: Cyber B3
      isolate_ports: false
      subnet: 10.20.23.0/24
      gateway: 10.20.23.1
      dhcp_start: 10.20.23.100
      dhcp_end: 10.20.23.199
      snat: true

    - name: cyberb4
      alias: Cyber B4
      isolate_ports: false
      subnet: 10.20.24.0/24
      gateway: 10.20.24.1
      dhcp_start: 10.20.24.100
      dhcp_end: 10.20.24.199
      snat: true
