proxmox_api_host: "10.64.62.200"
proxmox_api_user: "ansible@pve"
proxmox_api_token_id: "automation"
proxmox_api_token_secret: "91598b42-07fd-4975-befb-db0ca0cb028f"
proxmox_validate_certs: false

teachers_file: "/home/alex/cyberlab-infra/data/teachers.yml"
sections_file: "/home/alex/cyberlab-infra/data/sections.yml"
slots_file: "/home/alex/cyberlab-infra/data/slots.yml"
policy_file: "/home/alex/cyberlab-infra/data/policy.yml"
generated_students_file: "/home/alex/cyberlab-infra/private/generated/students.yml"
