- name: Create Proxmox ACLs
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - ../group_vars/all.yml
  module_defaults:
    group/community.proxmox.proxmox:
      api_host: "{{ proxmox_api_host }}"
      api_user: "{{ proxmox_api_user }}"
      api_token_id: "{{ proxmox_api_token_id }}"
      api_token_secret: "{{ proxmox_api_token_secret }}"
      validate_certs: "{{ proxmox_validate_certs }}"
  vars:
    sections_data: "{{ lookup('file', sections_file) | from_yaml }}"
    generated_students: "{{ lookup('file', generated_students_file) | from_yaml }}"
    proxmox_realm: "pve"

  tasks:
    - name: Give each student access to their own pool
      community.proxmox.proxmox_access_acl:
        path: "/pool/{{ item.proxmox_pool }}"
        type: user
        ugid: "{{ item.username }}@{{ proxmox_realm }}"
        roleid: "PVEVMUser"
        propagate: true
        state: present
      loop: "{{ generated_students.students }}"

    - name: Give teacher section group access to section shared pool
      community.proxmox.proxmox_access_acl:
        path: "/pool/{{ item.value.proxmox.shared_pool }}"
        type: group
        ugid: "{{ item.value.proxmox.teacher_group }}"
        roleid: "PVEVMAdmin"
        propagate: true
        state: present
      loop: "{{ sections_data.sections | dict2items }}"
