all:
  vars:
    proxmox_sdn:
      zone:
        name: virtnet
        type: simple
        dhcp: dnsmasq
        ipam: pve
        mtu: 1460

      vnets:
        - name: prov0
          alias: Provisioning Network
          isolate_ports: false

      subnets:
        - name: prov0
          subnet: 10.30.0.0/24
          gateway: 10.30.0.1
          snat: true

  children:
    proxmox_hosts:
      hosts:
        localhost:
          ansible_connection: local

    controller:
      hosts:
        localhost:
          ansible_connection: local

    proxmox_targets:
      hosts:
        pve1:
          ansible_host: 10.64.62.200
          ansible_user: root
          ansible_ssh_private_key_file: /root/.ssh/id_ed25519_controller
